# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- script: |
    echo "DEPLOYMENT_TOKEN value: $(DEPLOYMENT_TOKEN)"
  displayName: 'Debug DEPLOYMENT_TOKEN variable'

- task: AzureStaticWebApp@0
  inputs:
    app_location: 'src'
    api_location: ''
    output_location: '../build'
    skip_app_build: false
    skip_api_build: true
    deployment_environment: production
    azure_static_web_apps_api_token: $(DEPLOYMENT_TOKEN)
  displayName: 'Deploy to Azure Static Web Apps' 